---
title: "Visualizations & Summaries for Manuscript"
author: "Allison Theobold, Stacey Hancock, & Sara Mannheimer"
date: "12/30/2019"
output: html_document
---

# Set-up Options  

```{r}
library(tidyverse)
library(forcats)
library(viridis)
library(RColorBrewer)
```

# Read in Data  

```{r data}
pre_survey <- read_csv("all_ws_presurvey_clean.csv")

post_assessment <- read_csv("all_ws_postassessment_clean.csv")

```


# Summarizing Department & Occupation Attendance

```{r}
attendance <- pre_survey %>%
  rename(Department = department, 
         Occupation = occupation) %>% 
  mutate(Department = case_when(Department == 
                                  "Land Resources Environmental Science" ~ 
                                  "LRES",
                                Department == 
                                  "Mathematics/Statistics/Data Science" ~ 
                                  "Math/Stat/Data Science",
                                Department == 
                                  "Animal and Range Sciences" ~ 
                                  "Animal & Range Sciences",
                                Department == 
                                  "Biochemistry/Microbiology" ~ 
                                  "Biochem/Microbio", 
                                TRUE ~ Department)) %>% 
  group_by(Department, Occupation) %>%
  summarize(Freq = n()) %>% 
  arrange(desc(Freq)) %>% 
  ungroup()

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", 
               "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

attendance %>%
  mutate(Department = case_when(Department == 
                                  "Land Resources Environmental Science" ~ 
                                  "LRES",
                                Department == 
                                  "Mathematics/Statistics/Data Science" ~ 
                                  "Math/Stat/Data Science", 
                                Department == 
                                  "Animal and Range Sciences" ~ 
                                  "Animal & Range Sciences",
                                Department == 
                                  "Biochemistry/Microbiology" ~ 
                                  "Biochem/Microbio", 
                                TRUE ~ Department), 
         Department = factor(Department,
                             levels = unique(attendance$Department))) %>% 
  ggplot(mapping = aes(x = Department, y = Freq, fill = Occupation)) + 
  geom_bar(stat = "identity") + 
  ylim(0, 40) +
  labs(x = "Department Affiliation") + 
  theme_classic() +
  theme(axis.text.x = element_text(angle = -75, hjust = 0, vjust = 0.5, 
                                   size = 10), 
        axis.title.y = element_blank(),
        axis.title.x = element_text(size = 12), 
        axis.text.y = element_text(size = 12),
        legend.position = "top", 
        legend.text = element_text(size = 10), 
        legend.title = element_text(size = 10)) + 
  scale_fill_brewer(palette = "Paired")
  
# ggsave(plot, file = "better_colors_attendance.png", dpi = 300, width = 7, height = 7)
```


# Summarizing Programming Languages  

```{r}
all_survey %>% 
  gather(python:SQL, key = "language", value = "familiar") %>% 
  filter(familiar == "Yes") %>% 
  count(language) %>% 
  arrange(desc(n))

```


# Summarizing Data Storage  

```{r}
all_survey %>% 
  gather(store_excel:store_other, key = "storage method", value = "used") %>% 
  filter(used == "Yes") %>% 
  count(`storage method`) %>% 
  arrange(desc(n))

```


# Summarizing Data Collection Experiences

```{r}
all_survey %>% 
  gather(self_collect:no_collect, 
         key = "collection", value = "participated") %>% 
  filter(participated == "Yes") %>% 
  count(collection) %>% 
  arrange(desc(n))

```


# Summarizing Reasons for Attending  

```{r}
all_survey %>% 
  gather(research_help:professional_develop, 
         key = "reason", value = "agreed") %>% 
  filter(agreed == "Yes") %>% 
  count(reason) %>% 
  arrange(desc(n))

```


# Summarizing Resources Used  

```{r}
all_survey %>% 
  gather(no_resources:internet_resources, 
         key = "resource", value = "used") %>% 
  filter(used == "Yes") %>% 
  count(resource) %>% 
  arrange(desc(n))

```


# Summarizing Workshop Attendees Who Returned for Additional Workshops 

```{r}
intro_intermed <- all_ws %>% 
                    filter(workshop %in% 
                             c("Introduction to R", "Intermediate R"), 
                           semester %in% c("f18", "s19"))


intro_intermed %>% 
  filter(!is.na(identifier)) %>%
  group_by(identifier) %>% 
  summarize(count = n()) %>% 
  filter(count > 1)

## 8/63 came back to Intermediate R


intro_intermed %>% 
  filter(is.na(identifier)) %>%
  group_by(last_name) %>% 
  summarize(count = n()) %>% 
  filter(count > 1)

## 3/42 came back to Intermediate R

```

